<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007133215 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(200) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE commentaire ADD parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE commentaire ALTER note DROP NOT NULL');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC727ACA70 FOREIGN KEY (parent_id) REFERENCES commentaire (id)');
        $this->addSql('CREATE INDEX IDX_67F068BC727ACA70 ON commentaire (parent_id)');
        $this->addSql('ALTER TABLE ville ADD region_id INT NOT NULL');
        $this->addSql('ALTER TABLE ville ADD CONSTRAINT FK_43C3D9C398260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_43C3D9C398260155 ON ville (region_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE region');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC727ACA70');
        $this->addSql('DROP INDEX IDX_67F068BC727ACA70');
        $this->addSql('ALTER TABLE commentaire DROP parent_id');
        $this->addSql('ALTER TABLE commentaire ALTER note SET NOT NULL');
        $this->addSql('ALTER TABLE ville DROP CONSTRAINT FK_43C3D9C398260155');
        $this->addSql('DROP INDEX IDX_43C3D9C398260155');
        $this->addSql('ALTER TABLE ville DROP region_id');
    }
}
